import type { Social } from '@/lib/types/home'

export const socialMedia = [
    {
        id: '1',
        title: 'Twitter',
        url: 'https://twitter.com/yigityalim',
        color: [{ hex: '#1DA1F2' }],
        username: '@yigityalim',
        social: 'twitter',
    },
    {
        id: '2',
        title: 'Github',
        url: 'https://github.com/yigityalim',
        color: [{ hex: '#181717' }],
        username: '@yigityalim',
        social: 'github',
    },
    {
        id: '3',
        title: 'Linkedin',
        url: 'https://www.linkedin.com/in/yigityalim/',
        color: [{ hex: '#0077B5' }],
        username: '@yigityalim',
        social: 'linkedin',
    },
    {
        id: '4',
        title: 'Instagram',
        url: 'https://www.instagram.com/yigityalim/',
        color: [{ hex: '#833ab4' }],
        username: '@yigityalim',
        social: 'instagram',
    },
    {
        id: '5',
        title: 'Snapchat',
        url: 'https://www.snapchat.com/add/yigityalim',
        color: [{ hex: '#FFFC00' }],
        username: '@yigityalim',
        social: 'snapchat',
    },
    {
        id: '6',
        title: 'Discord',
        url: 'https://discord.com/users/1234567890',
        color: [{ hex: '#7289DA' }],
        username: '@yigityalim',
        social: 'discord',
    },
    {
        id: '7',
        title: 'Spotify',
        url: 'https://open.spotify.com/user/yigityalim',
        color: [{ hex: '#1DB954' }],
        username: '@yigityalim',
        social: 'spotify',
    },
] satisfies Social[]
