import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import React from 'react'
import { cn } from 'lib/utils'

import Footer from 'components/Footer'
import Header from 'components/Header'

import Providers from 'components/Providers/clientSideProvider'

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={cn('font-sans antialiased', fontSans.variable)}>
                <Providers attribute='class' defaultTheme='system' enableSystem>
                    <Header />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    )
}
